version: "3"

services:
    redis:
        container_name: crimes_redis_cache
        image: redis:alpine
        networks:
            - app-network

    crimes_zookeeper_container:
        image: wurstmeister/zookeeper:latest

    crimes_kafka_container:
        image: wurstmeister/kafka:2.11-1.1.1
        links:
            - crimes_zookeeper_container
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    crimes_container:
        image: crimes_image
        env_file: .env
        links:
            - pg_container
            - mongodb_container
            - redis:crimes_redis_cache
        depends_on:
            - pg_container
            - mongodb_container
            - redis
        networks:
            - app-network

    pg_container:
        image: postgres
        networks:
            - app-network
        volumes:
            - ./pg_container:/var/lib/postgresql/data

    mongodb_container:
        image: mongo:latest
        volumes:
            - ./mongodb_data_container:/data/db

networks:
    app-network:
        driver: bridge

volumes:
    mongodb_data_container:
